baseURL:         "http://radardoalagamento.org.br"
languageCode:    "pt-br"
title:           "Radar do alagamento"
disableKinds:    ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT: true
metaDataFormat:  "yaml"
enableMissingTranslationPlaceholders: true
defaultContentLanguage: pt
disableFastRender: true
ignoreFiles: [ "\\.tmp$", "\\.tmp\\-browserify" ]
stepAnalysis: true
templateMetrics: true
pluralizeListTitles: false

FootnoteReturnLinkContents: "↩"

params:
  description: "O Radar do Alagamento tem como base os dados sensores espalhados por todo a cidade. Além dos sensores da prefeitura, também possível que você, morador, possa construir e instalar o seu próprio sensor e integrá-lo a nossa base de dados."
  subtitle:      "Radar do alagamento"
  authorName:    "Natiene"
  gitHubUser:    "AppCivico"

  author:
    Radar:
      name: "Radar do Alagamento"
      link: "http://radardoalagamento.org.br"
      logo: ""
